### PR TITLE
Improved checking for homepage and usage of .Site.BaseURL

### PR DESCRIPTION
**Pull request by sdebruyn**
Continued work of https://github.com/key-amb/hugo-theme-bootie-docs/pull/2

### CODE REVIEW

**Comment by key-amb** [comment]
Errors about `$isHomePage` disappeared.
But errors of `.Site.BaseURL` still appear and still fails to output valid HTML.

```
$ hugo -v
INFO: 2015/07/20 Using config file: /Users/key-amb/gitrepos/bootie-docs-demo/config.toml
INFO: 2015/07/20 syncing from /Users/key-amb/gitrepos/bootie-docs-demo/themes/SamuelDebruyn-bootie-docs/static to /Users/key-amb/gitrepos/bootie-docs-demo/public/
INFO: 2015/07/20 syncing from /Users/key-amb/gitrepos/bootie-docs-demo/static/ to /Users/key-amb/gitrepos/bootie-docs-demo/public/
INFO: 2015/07/20 found taxonomies: map[string]string{"tag":"tags", "category":"categories"}
ERROR: 2015/07/20 template: theme/partials/header.html:38:41: executing "theme/partials/header.html" at <.Site.BaseURL>: can't evaluate field Site in type interface {} in theme/partials/header.html
ERROR: 2015/07/20 template: theme/partials/header.html:38:41: executing "theme/partials/header.html" at <.Site.BaseURL>: can't evaluate field Site in type interface {} in theme/partials/header.html
ERROR: 2015/07/20 template: theme/partials/sidebar-list.html:6:41: executing "theme/partials/sidebar-list.html" at <.Site.BaseURL>: can't evaluate field Site in
 type hugolib.WeightedPages in theme/partials/sidebar-list.html
ERROR: 2015/07/20 template: theme/partials/header.html:38:41: executing "theme/partials/header.html" at <.Site.BaseURL>: can't evaluate field Site in type inter
face {} in theme/partials/header.html
ERROR: 2015/07/20 template: theme/partials/header.html:38:41: executing "theme/partials/header.html" at <.Site.BaseURL>: can't evaluate field Site in type inter
face {} in theme/partials/header.htmlERROR: 2015/07/20 template: theme/partials/sidebar-list.html:6:41: executing "theme/partials/sidebar-list.html" at <.Site.BaseURL>: can't evaluate field Site in
 type hugolib.WeightedPages in theme/partials/sidebar-list.html
ERROR: 2015/07/20 template: theme/partials/sidebar-list.html:6:41: executing "theme/partials/sidebar-list.html" at <.Site.BaseURL>: can't evaluate field Site in
 type hugolib.WeightedPages in theme/partials/sidebar-list.htmlERROR: 2015/07/20 template: theme/partials/sidebar-list.html:6:41: executing "theme/partials/sidebar-list.html" at <.Site.BaseURL>: can't evaluate field Site in
 type hugolib.WeightedPages in theme/partials/sidebar-list.html
ERROR: 2015/07/20 template: theme/partials/header.html:38:41: executing "theme/partials/header.html" at <.Site.BaseURL>: can't evaluate field Site in type inter
face {} in theme/partials/header.htmlERROR: 2015/07/20 template: theme/partials/sidebar-list.html:6:41: executing "theme/partials/sidebar-list.html" at <.Site.BaseURL>: can't evaluate field Site in
 type hugolib.WeightedPages in theme/partials/sidebar-list.html
ERROR: 2015/07/20 template: theme/partials/header.html:38:41: executing "theme/partials/header.html" at <.Site.BaseURL>: can't evaluate field Site in type inter
face {} in theme/partials/header.htmlERROR: 2015/07/20 template: theme/partials/sidebar-list.html:6:41: executing "theme/partials/sidebar-list.html" at <.Site.BaseURL>: can't evaluate field Site in
 type hugolib.WeightedPages in theme/partials/sidebar-list.html
ERROR: 2015/07/20 template: theme/partials/header.html:38:41: executing "theme/partials/header.html" at <.Site.BaseURL>: can't evaluate field Site in type inter
face {} in theme/partials/header.html
ERROR: 2015/07/20 template: theme/partials/sidebar-single.html:15:37: executing "theme/partials/sidebar-single.html" at <.Site.BaseURL>: can't evaluate field Site in type hugolib.WeightedPages in theme/partials/sidebar-single.html
ERROR: 2015/07/20 template: theme/partials/header.html:38:41: executing "theme/partials/header.html" at <.Site.BaseURL>: can't evaluate field Site in type interface {} in theme/partials/header.html
ERROR: 2015/07/20 template: theme/partials/sidebar-single.html:15:37: executing "theme/partials/sidebar-single.html" at <.Site.BaseURL>: can't evaluate field Site in type hugolib.WeightedPages in theme/partials/sidebar-single.html
ERROR: 2015/07/20 template: theme/partials/header.html:38:41: executing "theme/partials/header.html" at <.Site.BaseURL>: can't evaluate field Site in type interface {} in theme/partials/header.html
ERROR: 2015/07/20 template: theme/partials/sidebar-single.html:15:37: executing "theme/partials/sidebar-single.html" at <.Site.BaseURL>: can't evaluate field Site in type hugolib.WeightedPages in theme/partials/sidebar-single.html
ERROR: 2015/07/20 template: theme/partials/header.html:38:41: executing "theme/partials/header.html" at <.Site.BaseURL>: can't evaluate field Site in type interface {} in theme/partials/header.html
ERROR: 2015/07/20 template: theme/partials/sidebar-single.html:15:37: executing "theme/partials/sidebar-single.html" at <.Site.BaseURL>: can't evaluate field Site in type hugolib.WeightedPages in theme/partials/sidebar-single.html
ERROR: 2015/07/20 template: theme/partials/header.html:38:41: executing "theme/partials/header.html" at <.Site.BaseURL>: can't evaluate field Site in type interface {} in theme/partials/header.html
WARN: 2015/07/20 Unable to locate layout for 404 page: [404.html theme/404.html]
0 draft content   
0 future content  
4 pages created   
0 paginator pages created
2 tags created
2 categories created
in 29 ms
```

**Comment by sdebruyn** [comment]
What does `hugo version` say?

**Comment by key-amb** [comment]
```
$ hugo version
Hugo Static Site Generator v0.14 BuildDate: 2015-06-02T21:43:08+09:00
```

**Comment by sdebruyn** [comment]
Well, I'm out of ideas. It seems like it doesn't recognize `.Site.BaseURL`... Maybe @bep or @spf13 could chime in here?

**Comment by bep** [comment]
There are many errors here.

They seem to have in common a confusion about which context is sent to the partials:

```
{{ partial "sidebar-list.html" . }}
```

Make sure that the "." above is the top-level node.

**Comment by sdebruyn** [comment]
The `partial` statements are only found in _index.html_, _list.html_ and _single.html_. The error only appears with `.Site.BaseURL` while all other `.Site....` variables seem to work.
I also don't get why I can't recreate these errors... (I'm on Windows 8.1 x64)

**Comment by key-amb** [comment]
Looks complicated.
Maybe difference between Windows and Mac?

Anyway, I don't want to merge this PR while there're problems in my environment.
If you can fix the problem, I will check again.

BTW do you have any problem using this theme? If no, I'd like to close this PR for now.

**Comment by sdebruyn** [comment]
Well, I created a Wercker step to validate themes. The step tests themes against an example site made by @spf13. The modified theme validates just fine... Did you try cloning everything in a new directory?

I agree that it's best to not merge this if you're having problems. I'll modify the PR to only include the isHomePage fixes since that didn't cause any problems in your environment.

**Pull request closed without merging**
